% =========================================================================
% Purpose: Demonstrates the extraction of RSRD features from fMRI time series

% This example uses a small demonstration dataset containing time-series data 
% from 20 ROIs recorded from a single HCP-YA participant. Feature extraction 
% is performed using a custom wrapper function (`extract_hctsa_features`), 
% which formats the input and computes a curated set of 44 RSRD features 
% defined in INP_ops_RSRD44.txt. The script further demonstrates how to load 
% and interpret the resulting feature matrix and quality control annotations 
% from the hctsa output file.

% Requirements:
%   - hctsa toolbox (https://github.com/benfulcher/hctsa)
%   - Tested with hctsa version 1.06; other versions may require adjustments.
% =========================================================================

% -------------------------------------------------------------------------
% STEP 1: Set up the environment
% -------------------------------------------------------------------------
% Ensure that the hctsa toolbox has been properly installed:
% → https://github.com/benfulcher/hctsa
% This implementation is based on hctsa version 1.06.
% Update the path below to reflect your local hctsa installation.
addpath(genpath('/Users/tianx/Documents/MATLAB/Toolboxes/hctsa'));
% Define the root path of the current project
project_path = '/Users/tianx/Documents/academic/manuscripts/RSRD/github/RSRD_BWAS';

% -------------------------------------------------------------------------
% STEP 2: Define input parameters
% -------------------------------------------------------------------------
% Identifier for the dataset (must match the prefix of *_INP.mat)
% This demo loads the file: /demo/TS_INP.mat
% The .mat file contains two variables:
%   - 'data'   : a time-series matrix of shape [1200 × 20], where each column 
%                corresponds to one ROI time series.
%   - 'labels' : a cell array of region names (e.g., 'region_1', 'region_2', ...)
data_label = 'TS'; 

% Feature set to extract:
%   - 'all'     : full hctsa feature set (~7700 features)
%   - 'RSRD44'  : 44 refined features used in the present study
feature_set = 'RSRD44';

% Directory containing the input time-series matrix (e.g., TS_INP.mat)
data_dir = fullfile(project_path, 'analysis', '01_RefinedRSRD', 'demo');

% Path to the operations file (required only if feature_set ≠ 'all')
% Note: When 'all' is selected, hctsa will use the default operations file.
ops_file = fullfile(project_path, 'analysis', '01_RefinedRSRD', 'INP_ops_RSRD44.txt');

% -------------------------------------------------------------------------
% STEP 3: Execute feature extraction
% -------------------------------------------------------------------------
% Arguments:
%   data_label     : identifier for the time-series dataset
%   data_dir       : folder containing the *_INP.mat file
%   feature_set    : selected feature set to extract ('all' or 'RSRD44')
%   ops_file       : path to the operations file (required for non-default sets)
%   true           : enables parallel computation
%   8              : number of parallel workers

extract_hctsa_features(data_label, ...
                       data_dir, ...
                       feature_set, ...
                       ops_file, ...
                       true, ...
                       8);

% -------------------------------------------------------------------------
% STEP 4: Check output
% -------------------------------------------------------------------------
% Load the output .mat file generated by hctsa (contains feature matrix and metadata)
rsrd44_out = load(fullfile(project_path, 'code', '01_RefinedRSRD', 'demo', 'TSRSRD44_OUT.mat'));

% Extract the main feature matrix (rows = time series, columns = features)
% Here: 20 ROIs × 44 features
feature_mat = rsrd44_out.TS_DataMat;

% Extract quality control labels for each feature computation
% 0 = successfully computed; nonzero = flagged for issues (e.g., NaNs, constant input, etc.)
% See documentation: https://time-series-features.gitbook.io/hctsa-manual/installing-and-using-hctsa/setup/hctsa_structure#quality-labels
feature_quality = rsrd44_out.TS_Quality;

% Extract feature metadata table: names, functions, and descriptions of each operation
feature_info = rsrd44_out.Operations;

